/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Auth: typeof import('./../views/Auth.vue')['default']
    BackButton: typeof import('./../components/Button/BackButton.vue')['default']
    BackTopButton: typeof import('./../components/Button/BackTopButton.vue')['default']
    BottomButton: typeof import('./../components/Button/BottomButton.vue')['default']
    BottomNav: typeof import('./../layout/BottomNav.vue')['default']
    Cart: typeof import('./../views/cart/Cart.vue')['default']
    CartList: typeof import('./../views/cart/CartList/CartList.vue')['default']
    CategoryList: typeof import('./../views/home/CategoryList.vue')['default']
    Counter: typeof import('./../components/Counter.vue')['default']
    FixedButton: typeof import('./../components/Button/FixedButton.vue')['default']
    FormInput: typeof import('./../components/FormInput.vue')['default']
    Home: typeof import('./../views/home/Home.vue')['default']
    Layout: typeof import('./../layout/Layout.vue')['default']
    Login: typeof import('./../views/Login.vue')['default']
    Notification: typeof import('./../components/Notification/Notification.vue')['default']
    NotificationItem: typeof import('./../components/Notification/NotificationItem.vue')['default']
    Product: typeof import('./../views/Product.vue')['default']
    ProductList: typeof import('./../views/products/ProductList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./../views/Search.vue')['default']
    Signup: typeof import('./../views/Signup.vue')['default']
    User: typeof import('./../views/User.vue')['default']
  }
}
